Repository clockwise-software/copper, pull requests merged in 2021-03, with the labels that each got.

#3 Add team contract
  TEAMCONTRACT.md
Labels: documentation, enhancement

#16 Update DB Schema
  bootcamp.db
  database-golden.db
Labels: enhancement

#17 Added search options in EmployeeSearch.html
  src/templates/EmployeeSearch.html
Labels: enhancement, frontend

#18 Updated SQL Command in SimpleServer.py and updated Jinja + Template
  src/SimpleServer.py
  src/templates/Employee.html
Labels: backend, enhancement
